In [2]:
import numpy as np
import torch

In [3]:
a = torch.tensor([2,4,6,8])
a.pow(0.5)


tensor([1.4142, 2.0000, 2.4495, 2.8284])

In [4]:
b = np.array([1,2,3])

In [5]:
np.diag(b)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [6]:
np.power(b, -0.5)

array([1.        , 0.70710678, 0.57735027])

In [7]:
a = np.array([1,2,3])
b = np.array([2,3,4])

np.outer(a,b)

array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12]])

In [8]:
a.T

array([1, 2, 3])

In [13]:
a = np.array([1,2,3])
c = np.array([[1,2,3], [2,3,4], [7,8,9]])

In [14]:
c

array([[1, 2, 3],
       [2, 3, 4],
       [7, 8, 9]])

In [15]:
c.T

array([[1, 2, 7],
       [2, 3, 8],
       [3, 4, 9]])

In [22]:
c+c.T

array([[ 2,  4, 10],
       [ 4,  6, 12],
       [10, 12, 18]])

In [23]:
d = np.fill_diagonal(c+c.T, 0)

In [24]:
d

In [28]:
f = np.zeros((3, 3), int)
np.fill_diagonal(f, 5)

In [29]:
f

array([[5, 0, 0],
       [0, 5, 0],
       [0, 0, 5]])

In [2]:
import numpy as np

a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [5]:
a / a.max(axis=1).reshape(-1,1)

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

In [6]:
adj_matrix = np.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]])

# Find the indices where the elements are non-zero
rows, cols = np.where(adj_matrix != 0)

In [1]:
import torch

In [3]:
1.01 - torch.tensor([0.9, 0.8, 0.1])

tensor([0.1100, 0.2100, 0.9100])